In [1]:
# A DataFrame is a 2d labelled array.
# We can make a DataFrame either using a dictionary of lists, list of lists(can also use numpy arrays) and csv or json or excel(read_excel) or sql(read_sql)

In [2]:
import pandas as pd
info = {
    "Name": ["Umar", "Rahul", "John"],
    "CGPA": [6.5, 7.5, 9.5]
}

df = pd.DataFrame(info)
df

    Name  CGPA
0   Umar   6.5
1  Rahul   7.5
2   John   9.5

In [3]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [4]:
df.columns

Index(['Name', 'CGPA'], dtype='object')

In [5]:
df2 = pd.DataFrame([["Umar", 22], ["John", 21]], columns = ["Name", "Age"])
df2

   Name  Age
0  Umar   22
1  John   21

In [6]:
df3 = pd.read_csv("employee_data.csv")
df4 = pd.read_json("employee_data.json")
df3.head() #First 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [7]:
df3.tail() #Last 5 rows

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [8]:
df3.sample() #A random row. Can also pass values in these three functions

   ID Name  Age Department  Salary
1   2  Bob   32         IT   72000

In [9]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [10]:
df3.shape

(10, 5)

In [11]:
df.describe() # Info about all the numerical data

           CGPA
count  3.000000
mean   7.833333
std    1.527525
min    6.500000
25%    7.000000
50%    7.500000
75%    8.500000
max    9.500000

In [12]:
df3.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [13]:
df3.nunique() # No of unique entries

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64