In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("globalAirQuality.csv") # Returns a panda data frame

In [3]:
df.sample(2)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
11991,2025-11-09 09:25:17.554219,AU,Sydney,-33.869,151.209,54.983,44.125,33.643,7.572,69.561,0.827,109,7.194,25.543,5.538
17557,2025-11-16 07:25:17.554219,FI,Helsinki,60.170,24.938,61.715,72.904,26.652,6.215,26.673,0.330,123,6.324,29.168,1.796

In [4]:
df.shape

(18000, 15)

In [5]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [6]:
# Selecting data

In [7]:
df[["aqi", "co", "humidity"]] #For selecting columns

       aqi     co  humidity
0      108  1.096    70.168
1       90  1.075    80.088
2       84  0.977    62.783
3      158  0.230    89.153
4       97  1.085    76.499
...    ...    ...       ...
17995  103  1.028    52.443
17996  105  0.644    85.678
17997  122  0.947    72.311
17998   95  0.868    31.880
17999   88  0.848    59.104

[18000 rows x 3 columns]

In [8]:
df.loc[0] # To get a specific row, label based

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object

In [9]:
df.loc[0:2] # Slice

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [10]:
df.iloc[4] # Index based

timestamp      2025-11-04 22:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               21.083
pm10                               66.423
no2                                38.997
so2                                 6.919
o3                                 45.615
co                                  1.085
aqi                                    97
temperature                        13.632
humidity                           76.499
wind_speed                          4.017
Name: 4, dtype: object

In [11]:
df.iloc[0:2] # iloc only takes numeric index values

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [12]:
# Specific values
df.loc[0:3, ["country", "city"]]

  country      city
0      US  New York
1      US  New York
2      US  New York
3      US  New York

In [13]:
df.iloc[0:4, 1:3]

  country      city
0      US  New York
1      US  New York
2      US  New York
3      US  New York

In [14]:
# For specific values we generally use at and iat
df.at[0, "city"]

'New York'

In [15]:
df.iat[0, 2]

'New York'

In [16]:
cities = df["city"].copy() # We must put the copy() here as cities contain a view and any changes in that will reflect in the original data.
cities[0] = "Delhi"

In [17]:
# Filtering Data

In [18]:
data = df[(df["aqi"] > 200) & (df["temperature"] > 16)] ["country"] # (and -> &, not -> ~, or -> |)
data.iloc[0] # This will print as this selects the 0th index of data.
# data.loc[0], this will give an error as this is label based access and the 0th label is not in the data selected.

'GB'

In [19]:
# Queries

In [20]:
# Rules
# Expression as a string
# Column based refrence, means we can directly write the names of columns.
# Backticks for col_name with space of special characters
# Operators (&, |, ~, >=, >, <=, <, ==, etc)
# @ to refrence Python variables
# Chained comparisons

In [21]:
aqi_val = 200
df.query("aqi > @aqi_val & temperature > 16") ["country"]

745      GB
17458    FI
17529    FI
17815    CH
Name: country, dtype: object